### ISSUE TITLE
what's the difference between original version with ORB_SLAM3_GPU

### ISSUE THREAD

**Issue by Firststep2014** [chunibyo-wly/ORB_SLAM3_GPU#1]
as mentioned

**Comment by chunibyo-wly** [comment]
1. 这个仓库是按学长的思路改的，改动在其他分支下面，master没动过。
2. 主要改动是
     - orbextractor加了gpu，照着[这个](https://github.com/yunchih/ORB-SLAM2-GPU2016-final)抄的
     - 因为用的turtlebot，大部分时候是匀速，imu约束改成可切换匀变速的
3. 这个仓库其实已经废掉了，因为我在自己的环境下面原版的orb3跑不成功，原仓库issue里面也或多或少提过这个问题

**Comment by LauZanMo** [comment]
我之前用t265跑成功过orb3的代码，但是按照你这个思路改了orbextrator.cc和frame.cc之后提取的特征点就为0了，貌似有点问题？

**Comment by chunibyo-wly** [comment]
额是的，这个代码仓库是应付任务做的，不好意思。
我现在orb3的原版代码都没办法在实验室的设备上运行XD

**Comment by LauZanMo** [comment]
我们能加个QQ交流一下吗？我毕设做的是这个233

**Comment by chunibyo-wly** [comment]
老哥，qq发我邮箱吧，在我主页可以找到，我来加你

**Comment by Sherlock-hh** [comment]
大佬现在有没有实验出来？加上gpu速度时否会更快？我在jetson nano上跑的是2-5帧每s，有点慢OTZ？
